// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9kVhpjjkN2PuUV1M9EvaeWLS7TDzdcR0',
    appId: '1:530507993948:web:dcfa019941799ade52e799',
    messagingSenderId: '530507993948',
    projectId: 'twitter-clone-115',
    authDomain: 'twitter-clone-115.firebaseapp.com',
    storageBucket: 'twitter-clone-115.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3C6gqS-IkCmozneOYqEopB3Dn5M4B-ik',
    appId: '1:530507993948:android:7f480d40c8cd77eb52e799',
    messagingSenderId: '530507993948',
    projectId: 'twitter-clone-115',
    storageBucket: 'twitter-clone-115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMSjrY8tdQ30R30bSwUhqWxjFDaL0Vjs',
    appId: '1:530507993948:ios:24eecbf50c87dce252e799',
    messagingSenderId: '530507993948',
    projectId: 'twitter-clone-115',
    storageBucket: 'twitter-clone-115.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjMSjrY8tdQ30R30bSwUhqWxjFDaL0Vjs',
    appId: '1:530507993948:ios:a6ed32e965e6e46952e799',
    messagingSenderId: '530507993948',
    projectId: 'twitter-clone-115',
    storageBucket: 'twitter-clone-115.appspot.com',
    iosBundleId: 'com.example.twitterClone.RunnerTests',
  );
}
